### ISSUE TITLE
fail to open the __MACOSX.rar file

### ISSUE THREAD

**Issue by JokingYi** [chenshaohao1998/APWebWAIM_2023#1]
I can't open the file contained in the zip file, wonder if there are some mistakes.
![image](https://github.com/chenshaohao1998/APWebWAIM_2023/assets/23569247/d285d8e2-38a3-416b-aea9-0c6533ba2062)

**Comment by KidddChen** [comment]
I re-uploaded this file. This problem seems to be been solved. Can you try again?

**Comment by JokingYi** [comment]
Yes, it's solved, thanks.


| |
龙智辉
|
|
***@***.***
|
签名由网易邮箱大师定制
On 5/12/2023 ***@***.***> wrote：

I re-uploaded this file. This problem seems to be been solved. Can you try again?
